#!/usr/bin/env ruby


require 'httpclient'
require 'json'

api_key = ENV['COINBASE_API_KEY']
client = HTTPClient.new

buy_rate_str = client.get_content("https://coinbase.com/api/v1/prices/buy")
buy_rate = JSON.parse(buy_rate_str)['amount'].to_f

sell_rate_str = client.get_content("https://coinbase.com/api/v1/prices/sell")
sell_rate = JSON.parse(sell_rate_str)['amount'].to_f

bal_str = client.get_content("https://coinbase.com/api/v1/account/balance?api_key=#{api_key}")
bal = JSON.parse(bal_str)['amount'].to_f

sell_price_str = client.get_content("https://coinbase.com/api/v1/prices/sell?qty=#{bal}")
sell_price = JSON.parse(sell_price_str)['amount']

puts "Buy rate (1 BTC): #{buy_rate} USD"
puts "Sell rate (1 BTC): #{sell_rate} USD"

puts ""

puts "Current balance: #{bal} BTC"
puts "Current sell value: #{sell_price} USD"
